#!/usr/bin/env python3
"""
components/indicators/__init__.py
SuperBot - Indicator Registry

AUTO-GENERATED by discovery_indicators.py - DO NOT EDIT MANUALLY

Total Indicators: 95
Categories: 11

Usage:    from components.indicators import INDICATOR_REGISTRY, get_indicator_class
    
    # Get indicator class
    RSI = get_indicator_class("rsi")
    rsi = RSI(period=14)
"""

from typing import Dict, Any, List, Type
import importlib
from pathlib import Path

# Import enums
from components.indicators.indicator_types import IndicatorCategory, IndicatorType


# ============================================================================
# INDICATOR REGISTRY
# ============================================================================

INDICATOR_REGISTRY: Dict[str, Dict[str, Any]] = {

    # 'COMMUNITY' (2 indicators)

    'mavilimw': {
        'module': 'community.mavilimw',
        'class': 'MavilimW',
        'category': 'community',
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'MavilimW Indicator',
        'default_params': {'fmal': 3, 'smal': 5},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['mavw', 'mavw_prev', 'trend_direction']
    },

    'pmax': {
        'module': 'community.pmax',
        'class': 'PMax',
        'category': 'community',
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'PMax Indicator',
        'default_params': {'atr_period': 10, 'atr_multiplier': 3.0, 'ma_period': 10},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['long_stop', 'mavg', 'pmax', 'short_stop', 'trend_direction']
    },

    # INDICATORCATEGORY.BREAKOUT (5 indicators)

    'breakout_scanner': {
        'module': 'breakout.breakout_scanner',
        'class': 'BreakoutScanner',
        'category': IndicatorCategory.BREAKOUT,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Multi-Timeframe Breakout Scanner',
        'default_params': {'lookback': 20, 'confirmation': 2, 'volume_threshold': 1.5, 'momentum_period': 14},
        'requires_volume': True,
        'has_calculate_batch': True,
        'output_keys': ['breakout_score', 'direction', 'momentum', 'resistance', 'support']
    },

    'consolidation': {
        'module': 'breakout.consolidation',
        'class': 'Consolidation',
        'category': IndicatorCategory.BREAKOUT,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Consolidation Detector',
        'default_params': {'period': 20, 'atr_period': 14, 'lookback': 100, 'min_consolidation_bars': 10},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['atr_score', 'distribution_score', 'level', 'range_pct', 'range_score', 'time_score', 'value']
    },

    'range_breakout': {
        'module': 'breakout.range_breakout',
        'class': 'RangeBreakout',
        'category': IndicatorCategory.BREAKOUT,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Range Breakout',
        'default_params': {'period': 20, 'consolidation_threshold': 3.0, 'breakout_confirmation': 1, 'use_body': False},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['lower', 'middle', 'upper']
    },

    'squeeze_momentum': {
        'module': 'breakout.squeeze_momentum',
        'class': 'SqueezeMomentum',
        'category': IndicatorCategory.BREAKOUT,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'TTM Squeeze Momentum',
        'default_params': {'bb_period': 20, 'bb_std': 2.0, 'kc_period': 20, 'kc_atr_mult': 1.5, 'momentum_period': 12},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['momentum', 'squeeze']
    },

    'volatility_breakout': {
        'module': 'breakout.volatility_breakout',
        'class': 'VolatilityBreakout',
        'category': IndicatorCategory.BREAKOUT,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Volatility Breakout',
        'default_params': {'period': 20, 'std_dev': 2.0, 'width_threshold': 4.0, 'use_volume': True},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['lower', 'middle', 'percent_b', 'upper', 'width']
    },

    # INDICATORCATEGORY.COMBO (6 indicators)

    'ema_ribbon': {
        'module': 'combo.ema_ribbon',
        'class': 'EMARibbon',
        'category': IndicatorCategory.COMBO,
        'type': IndicatorType.MULTIPLE_VALUES,
        'description': 'EMA Ribbon (Multiple EMA Bands)',
        'default_params': {'ema_periods': None},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['ema_10', 'ema_100', 'ema_20', 'ema_200', 'ema_5', 'ema_50']
    },

    'macd_rsi': {
        'module': 'combo.macd_rsi',
        'class': 'MACDRSICombo',
        'category': IndicatorCategory.COMBO,
        'type': IndicatorType.MULTIPLE_VALUES,
        'description': 'MACD + RSI Kombine Stratejisi',
        'default_params': {'macd_fast': 12, 'macd_slow': 26, 'macd_signal': 9, 'rsi_period': 14, 'rsi_overbought': 70, 'rsi_oversold': 30},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['histogram', 'macd', 'rsi', 'signal']
    },

    'rsi_bollinger': {
        'module': 'combo.rsi_bollinger',
        'class': 'RSIBollinger',
        'category': IndicatorCategory.COMBO,
        'type': IndicatorType.BANDS,
        'description': 'RSI + Bollinger Bands Kombine Stratejisi',
        'default_params': {'rsi_period': 14, 'rsi_overbought': 70, 'rsi_oversold': 30, 'bb_period': 20, 'bb_std_dev': 2.0},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['bb_lower', 'bb_middle', 'bb_upper', 'percent_b', 'price', 'rsi']
    },

    'smart_grok': {
        'module': 'combo.smart_grok',
        'class': 'SmartGrok',
        'category': IndicatorCategory.COMBO,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Smart Money Concept (SMC) - Improved version',
        'default_params': {'obv_period': 20, 'rsi_period': 14, 'adx_period': 14, 'adx_threshold': 25.0, 'structure_lookback': 20, 'fvg_min_gap_percent': 0.015, 'ob_lookback': 15},
        'requires_volume': True,
        'has_calculate_batch': True,
        'output_keys': ['bos', 'choch', 'fvg_bear', 'fvg_bull', 'market_structure', 'ob_bear', 'ob_bull', 'smc_score', 'smc_signal']
    },

    'smart_money': {
        'module': 'combo.smart_money',
        'class': 'SmartMoney',
        'category': IndicatorCategory.COMBO,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Smart Money Concept (SMC) System',
        'default_params': {'obv_period': 20, 'rsi_period': 14, 'adx_period': 14, 'adx_threshold': 25, 'structure_lookback': 20},
        'requires_volume': True,
        'has_calculate_batch': True,
        'output_keys': ['adx', 'bos', 'confirmation', 'market_structure', 'minus_di', 'obv', 'obv_signal', 'plus_di', 'rsi', 'signal', 'smart_money_flow', 'strength', 'trend']
    },

    'triple_screen': {
        'module': 'combo.triple_screen',
        'class': 'TripleScreen',
        'category': IndicatorCategory.COMBO,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Elder\'s Triple Screen Trading System',
        'default_params': {'ema_fast': 13, 'ema_slow': 26, 'rsi_period': 13, 'rsi_overbought': 70, 'rsi_oversold': 30, 'use_macd': True},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['current_price', 'screen1', 'screen2', 'screen3_buy', 'screen3_sell']
    },

    # INDICATORCATEGORY.MOMENTUM (15 indicators)

    'apo': {
        'module': 'momentum.apo',
        'class': 'APO',
        'category': IndicatorCategory.MOMENTUM,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'APO (Absolute Price Oscillator)',
        'default_params': {'fast_period': 12, 'slow_period': 26},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['apo']
    },

    'awesome': {
        'module': 'momentum.awesome',
        'class': 'AwesomeOscillator',
        'category': IndicatorCategory.MOMENTUM,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Awesome Oscillator',
        'default_params': {'fast_period': 5, 'slow_period': 34},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['ao']
    },

    'cci': {
        'module': 'momentum.cci',
        'class': 'CCI',
        'category': IndicatorCategory.MOMENTUM,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Commodity Channel Index',
        'default_params': {'period': 20, 'overbought': 100, 'oversold': -100},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['cci']
    },

    'cmo': {
        'module': 'momentum.cmo',
        'class': 'CMO',
        'category': IndicatorCategory.MOMENTUM,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'CMO (Chande Momentum Oscillator)',
        'default_params': {'period': 14},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['cmo']
    },

    'mfi': {
        'module': 'momentum.mfi',
        'class': 'MFI',
        'category': IndicatorCategory.MOMENTUM,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Money Flow Index',
        'default_params': {'period': 14, 'overbought': 80, 'oversold': 20},
        'requires_volume': True,
        'has_calculate_batch': True,
        'output_keys': ['mfi']
    },

    'mom': {
        'module': 'momentum.mom',
        'class': 'MOM',
        'category': IndicatorCategory.MOMENTUM,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'MOM (Momentum Indicator)',
        'default_params': {'period': 10},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['mom']
    },

    'ppo': {
        'module': 'momentum.ppo',
        'class': 'PPO',
        'category': IndicatorCategory.MOMENTUM,
        'type': IndicatorType.MULTIPLE_VALUES,
        'description': 'PPO (Percentage Price Oscillator)',
        'default_params': {'fast_period': 12, 'slow_period': 26, 'signal_period': 9},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['histogram', 'ppo', 'signal']
    },

    'roc': {
        'module': 'momentum.roc',
        'class': 'ROC',
        'category': IndicatorCategory.MOMENTUM,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Rate of Change',
        'default_params': {'period': 12},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['roc']
    },

    'rsi': {
        'module': 'momentum.rsi',
        'class': 'RSI',
        'category': IndicatorCategory.MOMENTUM,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Relative Strength Index',
        'default_params': {'period': 14, 'overbought': 70, 'oversold': 30},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['rsi']
    },

    'rsidivergence': {
        'module': 'momentum.rsidivergence',
        'class': 'RSIDivergence',
        'category': IndicatorCategory.MOMENTUM,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'RSI Divergence',
        'default_params': {'rsi_period': 14, 'lookback': 5, 'min_strength': 30},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': []
    },

    'stochastic': {
        'module': 'momentum.stochastic',
        'class': 'Stochastic',
        'category': IndicatorCategory.MOMENTUM,
        'type': IndicatorType.MULTIPLE_VALUES,
        'description': 'Stochastic Oscillator',
        'default_params': {'k_period': 14, 'd_period': 3},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['d', 'k']
    },

    'stochasticrsi': {
        'module': 'momentum.stochasticrsi',
        'class': 'StochasticRSI',
        'category': IndicatorCategory.MOMENTUM,
        'type': IndicatorType.MULTIPLE_VALUES,
        'description': 'Stochastic RSI',
        'default_params': {'rsi_period': 14, 'stoch_period': 14, 'k_smooth': 3, 'd_smooth': 3, 'overbought': 80, 'oversold': 20, 'rsi_source': 0},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['crossover', 'd', 'k', 'stoch_rsi']
    },

    'tsi': {
        'module': 'momentum.tsi',
        'class': 'TSI',
        'category': IndicatorCategory.MOMENTUM,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'True Strength Index',
        'default_params': {'long_period': 25, 'short_period': 13, 'signal_period': 7},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['histogram', 'signal', 'tsi']
    },

    'ultimate': {
        'module': 'momentum.ultimate',
        'class': 'UltimateOscillator',
        'category': IndicatorCategory.MOMENTUM,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Ultimate Oscillator',
        'default_params': {'period1': 7, 'period2': 14, 'period3': 28, 'overbought': 70, 'oversold': 30},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['uo']
    },

    'williams_r': {
        'module': 'momentum.williams_r',
        'class': 'WilliamsR',
        'category': IndicatorCategory.MOMENTUM,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Williams %R',
        'default_params': {'period': 14, 'overbought': -20, 'oversold': -80},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['williams_r']
    },

    # INDICATORCATEGORY.PATTERNS (2 indicators)

    'candlestick_patterns': {
        'module': 'patterns.candlestick_patterns',
        'class': 'CandlestickPatterns',
        'category': IndicatorCategory.PATTERNS,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'components/indicators/patterns/candlestick_patterns.py',
        'default_params': {'doji_threshold': 0.1, 'shadow_ratio': 2.0, 'min_body_size': 0.0001},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['count', 'details', 'patterns']
    },

    'talib_patterns': {
        'module': 'patterns.talib_patterns',
        'class': 'TALibPatterns',
        'category': IndicatorCategory.PATTERNS,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'components/indicators/patterns/talib_patterns.py',
        'default_params': {},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['count', 'details', 'patterns']
    },

    # INDICATORCATEGORY.STATISTICAL (8 indicators)

    'cointegration': {
        'module': 'statistical.cointegration',
        'class': 'Cointegration',
        'category': IndicatorCategory.STATISTICAL,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Cointegration',
        'default_params': {'period': 50, 'reference_data': None, 'entry_threshold': 2.0, 'exit_threshold': 0.5, 'adf_significance': 0.05},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['is_cointegrated', 'spread', 'zscore']
    },

    'correlation': {
        'module': 'statistical.correlation',
        'class': 'Correlation',
        'category': IndicatorCategory.STATISTICAL,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Correlation',
        'default_params': {'period': 20, 'reference_data': None, 'high_correlation': 0.7, 'low_correlation': -0.7},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['correlation']
    },

    'linear_regression': {
        'module': 'statistical.linear_regression',
        'class': 'LinearRegression',
        'category': IndicatorCategory.STATISTICAL,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Linear Regression (OPTIMIZED VERSION 🚀)',
        'default_params': {'period': 20, 'forecast_periods': 1, 'min_r_squared': 0.5},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['forecast', 'intercept', 'r_squared', 'slope']
    },

    'percentile_rank': {
        'module': 'statistical.percentile_rank',
        'class': 'PercentileRank',
        'category': IndicatorCategory.STATISTICAL,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Percentile Rank (Percentile Rank)',
        'default_params': {'period': 20, 'overbought': 80, 'oversold': 20},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['percentile_rank']
    },

    'tsf': {
        'module': 'statistical.tsf',
        'class': 'TSF',
        'category': IndicatorCategory.STATISTICAL,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'TSF (Time Series Forecast)',
        'default_params': {'period': 14},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['tsf']
    },

    'typprice': {
        'module': 'statistical.typprice',
        'class': 'TYPPRICE',
        'category': IndicatorCategory.STATISTICAL,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'TYPPRICE (Typical Price)',
        'default_params': {},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['typprice']
    },

    'var': {
        'module': 'statistical.var',
        'class': 'VAR',
        'category': IndicatorCategory.STATISTICAL,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'VAR (Variance)',
        'default_params': {'period': 20},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['var']
    },

    'zscore': {
        'module': 'statistical.zscore',
        'class': 'ZScore',
        'category': IndicatorCategory.STATISTICAL,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Z-Score (Standart Sapma Skoru)',
        'default_params': {'period': 20, 'overbought': 2.0, 'oversold': -2.0},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['zscore']
    },

    # INDICATORCATEGORY.STRUCTURE (11 indicators)

    'bos': {
        'module': 'structure.bos',
        'class': 'BOS',
        'category': IndicatorCategory.STRUCTURE,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Break of Structure',
        'default_params': {'left_bars': 5, 'right_bars': 5, 'max_levels': 3, 'trend_strength': 3},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['bos']
    },

    'choch': {
        'module': 'structure.choch',
        'class': 'CHoCH',
        'category': IndicatorCategory.STRUCTURE,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Change of Character',
        'default_params': {'left_bars': 5, 'right_bars': 5, 'max_levels': 3, 'trend_strength': 3},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['choch']
    },

    'fvg': {
        'module': 'structure.fvg',
        'class': 'FVG',
        'category': IndicatorCategory.STRUCTURE,
        'type': IndicatorType.ZONES,
        'description': 'Fair Value Gap',
        'default_params': {'min_gap_percent': 0.1, 'max_zones': 5, 'fill_threshold': 0.5},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['fvg']
    },

    'gap': {
        'module': 'structure.gap',
        'class': 'Gap',
        'category': IndicatorCategory.STRUCTURE,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'components/indicators/structure/gap.py',
        'default_params': {'min_gap_percent': 0.05, 'max_zones': 50, 'max_age': 500},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['gap']
    },

    'ifvg': {
        'module': 'structure.ifvg',
        'class': 'iFVG',
        'category': IndicatorCategory.STRUCTURE,
        'type': IndicatorType.ZONES,
        'description': 'Inverse Fair Value Gap',
        'default_params': {'min_gap_percent': 0.1, 'lookback_bars': 10, 'min_distance': 3},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['ifvg']
    },

    'liquidityzones': {
        'module': 'structure.liquidityzones',
        'class': 'LiquidityZones',
        'category': IndicatorCategory.STRUCTURE,
        'type': IndicatorType.ZONES,
        'description': 'Liquidity Zones',
        'default_params': {'left_bars': 5, 'right_bars': 5, 'equal_tolerance': 0.1, 'max_zones': 5, 'sweep_lookback': 3},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': []
    },

    'lvvoid': {
        'module': 'structure.lvvoid',
        'class': 'LVVoid',
        'category': IndicatorCategory.STRUCTURE,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Liquidity Void',
        'default_params': {'min_gap_percent': 0.1, 'volume_threshold': 0.5, 'volume_period': 20, 'max_zones': 5},
        'requires_volume': True,
        'has_calculate_batch': True,
        'output_keys': ['lvvoid']
    },

    'market_structure': {
        'module': 'structure.market_structure',
        'class': 'MarketStructure',
        'category': IndicatorCategory.STRUCTURE,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Market Structure (Combined)',
        'default_params': {'enable_bos': True, 'enable_choch': True, 'enable_fvg': True, 'enable_ob': True, 'enable_liq': True, 'left_bars': 5, 'right_bars': 5},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['ms_bos_signal', 'ms_bos_trend', 'ms_bos_value', 'ms_choch_signal', 'ms_choch_trend', 'ms_choch_value', 'ms_fvg_signal', 'ms_fvg_zones', 'ms_liq_signal', 'ms_liq_zones', 'ms_ob_signal', 'ms_ob_zones', 'ms_overall_signal', 'ms_overall_strength', 'ms_overall_trend']
    },

    'orderblocks': {
        'module': 'structure.orderblocks',
        'class': 'OrderBlocks',
        'category': IndicatorCategory.STRUCTURE,
        'type': IndicatorType.ZONES,
        'description': 'Order Blocks',
        'default_params': {'strength_threshold': 1.0, 'max_blocks': 5, 'lookback': 20},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': []
    },

    'qml': {
        'module': 'structure.qml',
        'class': 'QML',
        'category': IndicatorCategory.STRUCTURE,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'QML ULTRA-OPTIMIZED (v4.0)',
        'default_params': {'left_bars': 5, 'right_bars': 5, 'lookback_bars': 30, 'break_threshold': 0.1},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['qml']
    },

    'smc': {
        'module': 'structure.smc',
        'class': 'SMC',
        'category': IndicatorCategory.STRUCTURE,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'SMC (Smart Money Concepts) Indicator',
        'default_params': {'left_bars': 5, 'right_bars': 5, 'max_levels': 5, 'trend_strength': 2, 'fvg_min_size_pct': 0.1, 'fvg_max_age': 50, 'ob_strength_threshold': 1.0, 'ob_max_blocks': 3, 'ob_enabled': True},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['bos', 'choch', 'fvg', 'smc_signal', 'swing_high', 'swing_low']
    },

    # INDICATORCATEGORY.SUPPORT_RESISTANCE (8 indicators)

    'camarilla': {
        'module': 'support_resistance.camarilla',
        'class': 'Camarilla',
        'category': IndicatorCategory.SUPPORT_RESISTANCE,
        'type': IndicatorType.LEVELS,
        'description': 'Camarilla Pivot Points',
        'default_params': {'period': 1},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['R1', 'R2', 'R3', 'R4', 'S1', 'S2', 'S3', 'S4']
    },

    'fib_retracement': {
        'module': 'support_resistance.fib_retracement',
        'class': 'FibonacciRetracement',
        'category': IndicatorCategory.SUPPORT_RESISTANCE,
        'type': IndicatorType.LEVELS,
        'description': 'Fibonacci Retracement',
        'default_params': {'lookback': 50},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['Fib_0.0', 'Fib_100.0', 'Fib_23.6', 'Fib_38.2', 'Fib_50.0', 'Fib_61.8', 'Fib_78.6']
    },

    'fibonacci_pivot': {
        'module': 'support_resistance.fibonacci_pivot',
        'class': 'FibonacciPivot',
        'category': IndicatorCategory.SUPPORT_RESISTANCE,
        'type': IndicatorType.LEVELS,
        'description': 'Fibonacci Pivot Points',
        'default_params': {'period': 1},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['P', 'R1', 'R2', 'R3', 'S1', 'S2', 'S3']
    },

    'pivotpoints': {
        'module': 'support_resistance.pivotpoints',
        'class': 'PivotPoints',
        'category': IndicatorCategory.SUPPORT_RESISTANCE,
        'type': IndicatorType.LEVELS,
        'description': 'Pivot Points',
        'default_params': {'period': 1},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['p', 'r1', 'r2', 'r3', 's1', 's2', 's3']
    },

    'sr': {
        'module': 'support_resistance.sr',
        'class': 'SupportResistance',
        'category': IndicatorCategory.SUPPORT_RESISTANCE,
        'type': IndicatorType.MULTIPLE_VALUES,
        'description': 'Support and Resistance Levels',
        'default_params': {'lookback': 50, 'num_levels': 5, 'tolerance': 0.5},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': []
    },

    'swing_points': {
        'module': 'support_resistance.swing_points',
        'class': 'SwingPoints',
        'category': IndicatorCategory.SUPPORT_RESISTANCE,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Swing Points',
        'default_params': {'left_bars': 5, 'right_bars': 5, 'lookback': 50},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['swing_high', 'swing_low']
    },

    'woodie': {
        'module': 'support_resistance.woodie',
        'class': 'Woodie',
        'category': IndicatorCategory.SUPPORT_RESISTANCE,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Woodie Pivot Points',
        'default_params': {'period': 1},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['P', 'R1', 'R2', 'S1', 'S2']
    },

    'zigzag': {
        'module': 'support_resistance.zigzag',
        'class': 'ZigZag',
        'category': IndicatorCategory.SUPPORT_RESISTANCE,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'ZigZag Indicator',
        'default_params': {'deviation': 5.0, 'depth': 12},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['pivot_type', 'value']
    },

    # INDICATORCATEGORY.TREND (19 indicators)

    'adx': {
        'module': 'trend.adx',
        'class': 'ADX',
        'category': IndicatorCategory.TREND,
        'type': IndicatorType.MULTIPLE_VALUES,
        'description': 'Average Directional Index',
        'default_params': {'period': 14, 'adx_threshold': 25},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['adx', 'minus_di', 'plus_di']
    },

    'aroon': {
        'module': 'trend.aroon',
        'class': 'Aroon',
        'category': IndicatorCategory.TREND,
        'type': IndicatorType.MULTIPLE_VALUES,
        'description': 'Aroon Indicator',
        'default_params': {'period': 25},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['aroon_down', 'aroon_osc', 'aroon_up']
    },

    'dema': {
        'module': 'trend.dema',
        'class': 'DEMA',
        'category': IndicatorCategory.TREND,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Double Exponential Moving Average',
        'default_params': {'period': 20},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['dema']
    },

    'donchian': {
        'module': 'trend.donchian',
        'class': 'DonchianChannel',
        'category': IndicatorCategory.TREND,
        'type': IndicatorType.BANDS,
        'description': 'Donchian Channel',
        'default_params': {'period': 20},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['lower', 'middle', 'upper']
    },

    'dx': {
        'module': 'trend.dx',
        'class': 'DX',
        'category': IndicatorCategory.TREND,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'DX (Directional Movement Index)',
        'default_params': {'period': 14},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['dx', 'minus_di', 'plus_di']
    },

    'ema': {
        'module': 'trend.ema',
        'class': 'EMA',
        'category': IndicatorCategory.TREND,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Exponential Moving Average',
        'default_params': {'period': 20, 'sma_seed': None},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['ema']
    },

    'hma': {
        'module': 'trend.hma',
        'class': 'HMA',
        'category': IndicatorCategory.TREND,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Hull Moving Average',
        'default_params': {'period': 20},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['hma']
    },

    'ichimoku': {
        'module': 'trend.ichimoku',
        'class': 'Ichimoku',
        'category': IndicatorCategory.TREND,
        'type': IndicatorType.LINES,
        'description': 'Ichimoku Cloud',
        'default_params': {'tenkan_period': 9, 'kijun_period': 26, 'senkou_b_period': 52, 'displacement': 26},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['chikou', 'kijun', 'senkou_a', 'senkou_b', 'tenkan']
    },

    'kama': {
        'module': 'trend.kama',
        'class': 'KAMA',
        'category': IndicatorCategory.TREND,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Kaufman Adaptive Moving Average',
        'default_params': {'period': 10, 'fast_period': 2, 'slow_period': 30},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['kama']
    },

    'macd': {
        'module': 'trend.macd',
        'class': 'MACD',
        'category': IndicatorCategory.TREND,
        'type': IndicatorType.MULTIPLE_VALUES,
        'description': 'Moving Average Convergence Divergence',
        'default_params': {'fast_period': 12, 'slow_period': 26, 'signal_period': 9},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['histogram', 'macd', 'signal']
    },

    'parabolic_sar': {
        'module': 'trend.parabolic_sar',
        'class': 'ParabolicSAR',
        'category': IndicatorCategory.TREND,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Parabolic SAR',
        'default_params': {'af_start': 0.02, 'af_increment': 0.02, 'af_max': 0.2},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['af', 'ep', 'sar', 'trend']
    },

    'sma': {
        'module': 'trend.sma',
        'class': 'SMA',
        'category': IndicatorCategory.TREND,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Simple Moving Average',
        'default_params': {'period': 20},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['sma']
    },

    'supertrend': {
        'module': 'trend.supertrend',
        'class': 'SuperTrend',
        'category': IndicatorCategory.TREND,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'SuperTrend Indicator',
        'default_params': {'period': 10, 'multiplier': 3.0},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['direction', 'lower', 'supertrend', 'trend', 'upper']
    },

    't3': {
        'module': 'trend.t3',
        'class': 'T3',
        'category': IndicatorCategory.TREND,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'T3 (Tillson T3 Moving Average)',
        'default_params': {'period': 5, 'vfactor': 0.7},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['t3']
    },

    'tema': {
        'module': 'trend.tema',
        'class': 'TEMA',
        'category': IndicatorCategory.TREND,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Triple Exponential Moving Average',
        'default_params': {'period': 20},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['tema']
    },

    'trima': {
        'module': 'trend.trima',
        'class': 'TRIMA',
        'category': IndicatorCategory.TREND,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'TRIMA (Triangular Moving Average)',
        'default_params': {'period': 20},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['trima']
    },

    'trix': {
        'module': 'trend.trix',
        'class': 'TRIX',
        'category': IndicatorCategory.TREND,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'TRIX (Triple Exponential Average)',
        'default_params': {'period': 15},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['trix']
    },

    'vwma': {
        'module': 'trend.vwma',
        'class': 'VWMA',
        'category': IndicatorCategory.TREND,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Volume Weighted Moving Average',
        'default_params': {'period': 20},
        'requires_volume': True,
        'has_calculate_batch': True,
        'output_keys': ['vwma']
    },

    'wma': {
        'module': 'trend.wma',
        'class': 'WMA',
        'category': IndicatorCategory.TREND,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Weighted Moving Average',
        'default_params': {'period': 20},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['wma']
    },

    # INDICATORCATEGORY.VOLATILITY (8 indicators)

    'atr': {
        'module': 'volatility.atr',
        'class': 'ATR',
        'category': IndicatorCategory.VOLATILITY,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Average True Range',
        'default_params': {'period': 14},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['atr']
    },

    'bollinger': {
        'module': 'volatility.bollinger',
        'class': 'BollingerBands',
        'category': IndicatorCategory.VOLATILITY,
        'type': IndicatorType.BANDS,
        'description': 'Bollinger Bands',
        'default_params': {'period': 20, 'std_dev': 2.0},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['lower', 'middle', 'upper']
    },

    'chandelier': {
        'module': 'volatility.chandelier',
        'class': 'ChandelierExit',
        'category': IndicatorCategory.VOLATILITY,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Chandelier Exit',
        'default_params': {'period': 22, 'multiplier': 3.0},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['long_stop', 'short_stop']
    },

    'keltner': {
        'module': 'volatility.keltner',
        'class': 'KeltnerChannel',
        'category': IndicatorCategory.VOLATILITY,
        'type': IndicatorType.BANDS,
        'description': 'Keltner Channel',
        'default_params': {'ema_period': 20, 'atr_period': 10, 'multiplier': 2.0},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['lower', 'middle', 'upper']
    },

    'natr': {
        'module': 'volatility.natr',
        'class': 'NATR',
        'category': IndicatorCategory.VOLATILITY,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Normalized Average True Range',
        'default_params': {'period': 14},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['natr']
    },

    'squeeze': {
        'module': 'volatility.squeeze',
        'class': 'TTMSqueeze',
        'category': IndicatorCategory.VOLATILITY,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'TTM Squeeze',
        'default_params': {'bb_period': 20, 'bb_std': 2.0, 'kc_period': 20, 'kc_atr_period': 20, 'kc_mult': 1.5},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['momentum', 'squeeze_on']
    },

    'standard_dev': {
        'module': 'volatility.standard_dev',
        'class': 'StandardDeviation',
        'category': IndicatorCategory.VOLATILITY,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Standard Deviation',
        'default_params': {'period': 20},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['std_dev']
    },

    'true_range': {
        'module': 'volatility.true_range',
        'class': 'TrueRange',
        'category': IndicatorCategory.VOLATILITY,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'True Range',
        'default_params': {},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['true_range']
    },

    # INDICATORCATEGORY.VOLUME (11 indicators)

    'ad': {
        'module': 'volume.ad',
        'class': 'AD',
        'category': IndicatorCategory.VOLUME,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Accumulation/Distribution',
        'default_params': {'signal_period': 10},
        'requires_volume': True,
        'has_calculate_batch': True,
        'output_keys': ['ad']
    },

    'adosc': {
        'module': 'volume.adosc',
        'class': 'ADOSC',
        'category': IndicatorCategory.VOLUME,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'ADOSC (Chaikin A/D Oscillator)',
        'default_params': {'fast_period': 3, 'slow_period': 10},
        'requires_volume': True,
        'has_calculate_batch': True,
        'output_keys': ['adosc']
    },

    'bop': {
        'module': 'volume.bop',
        'class': 'BOP',
        'category': IndicatorCategory.VOLUME,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'BOP (Balance of Power)',
        'default_params': {},
        'requires_volume': False,
        'has_calculate_batch': True,
        'output_keys': ['bop']
    },

    'cmf': {
        'module': 'volume.cmf',
        'class': 'CMF',
        'category': IndicatorCategory.VOLUME,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Chaikin Money Flow',
        'default_params': {'period': 20, 'buy_threshold': 0.05, 'sell_threshold': -0.05},
        'requires_volume': True,
        'has_calculate_batch': True,
        'output_keys': ['cmf']
    },

    'eom': {
        'module': 'volume.eom',
        'class': 'EOM',
        'category': IndicatorCategory.VOLUME,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Ease of Movement',
        'default_params': {'period': 14, 'divisor': 100000000},
        'requires_volume': True,
        'has_calculate_batch': True,
        'output_keys': ['eom']
    },

    'force_index': {
        'module': 'volume.force_index',
        'class': 'ForceIndex',
        'category': IndicatorCategory.VOLUME,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Force Index',
        'default_params': {'period': 13},
        'requires_volume': True,
        'has_calculate_batch': True,
        'output_keys': ['force_index']
    },

    'obv': {
        'module': 'volume.obv',
        'class': 'OBV',
        'category': IndicatorCategory.VOLUME,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'On Balance Volume',
        'default_params': {'signal_period': 20},
        'requires_volume': True,
        'has_calculate_batch': True,
        'output_keys': ['obv', 'obv_signal']
    },

    'volume_oscillator': {
        'module': 'volume.volume_oscillator',
        'class': 'VolumeOscillator',
        'category': IndicatorCategory.VOLUME,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Volume Oscillator',
        'default_params': {'fast_period': 5, 'slow_period': 10, 'signal_period': 10},
        'requires_volume': True,
        'has_calculate_batch': True,
        'output_keys': ['vo']
    },

    'volume_profile': {
        'module': 'volume.volume_profile',
        'class': 'VolumeProfile',
        'category': IndicatorCategory.VOLUME,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Volume Profile',
        'default_params': {'period': 50, 'bins': 24, 'value_area': 70.0},
        'requires_volume': True,
        'has_calculate_batch': True,
        'output_keys': ['poc', 'vah', 'val']
    },

    'vwap': {
        'module': 'volume.vwap',
        'class': 'VWAP',
        'category': IndicatorCategory.VOLUME,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'Volume Weighted Average Price',
        'default_params': {'period': 20},
        'requires_volume': True,
        'has_calculate_batch': True,
        'output_keys': ['vwap']
    },

    'vwap_bands': {
        'module': 'volume.vwap_bands',
        'class': 'VWAPBands',
        'category': IndicatorCategory.VOLUME,
        'type': IndicatorType.SINGLE_VALUE,
        'description': 'VWAP Bands',
        'default_params': {'period': 20, 'multiplier': 2.0},
        'requires_volume': True,
        'has_calculate_batch': True,
        'output_keys': ['lower', 'upper', 'vwap']
    },

}


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def get_indicator_class(name: str) -> Type:
    """
Import the Indicator class
    
    Args:
        name: Indicator name (e.g., 'rsi', 'bollinger')
    
    Returns:
        Indicator class
    """
    if name not in INDICATOR_REGISTRY:
        available = list(INDICATOR_REGISTRY.keys())
        raise ValueError(
            f"Indicator '{name}' not found!\n"
            f"Available: {len(available)} indicators"
        )
    
    info = INDICATOR_REGISTRY[name]
    
    # sys.modules hack - Fix "from indicators.X import" errors
    import sys
    import components.indicators
    import components.indicators.base_indicator
    import components.indicators.indicator_types
    sys.modules['indicators'] = sys.modules['components.indicators']
    sys.modules['indicators.base_indicator'] = sys.modules['components.indicators.base_indicator']
    sys.modules['indicators.indicator_types'] = sys.modules['components.indicators.indicator_types']
    
    # Import module
    module_path = f"components.indicators.{info['module']}"
    module = importlib.import_module(module_path)
    
    return getattr(module, info['class'])


def list_indicators(category: str = None) -> List[str]:
    """Indicator list"""
    if category:
        return [
            name for name, info in INDICATOR_REGISTRY.items()
            if info['category'] == category
        ]
    return list(INDICATOR_REGISTRY.keys())


def get_batch_capable_indicators() -> List[str]:
    """indicators that are part of the calculate_batch() function"""
    return [
        name for name, info in INDICATOR_REGISTRY.items()
        if info['has_calculate_batch']
    ]


def get_categories() -> List[str]:
    """Kategoriler"""
    categories = set(str(info['category']).split('.')[-1] for info in INDICATOR_REGISTRY.values())
    return sorted(categories)


def get_indicator_info(name: str) -> Dict[str, Any]:
    """
    Get indicator information
    
    Args:
        name: Indicator name
    
    Returns:
        Dict with indicator info
    """
    if name not in INDICATOR_REGISTRY:
        raise ValueError(f"Unknown indicator: '{name}'")
    
    return INDICATOR_REGISTRY[name].copy()


def get_registry_statistics() -> Dict[str, Any]:
    """
    Get registry statistics
    
    Returns:
        Dict with statistics
    """
    total = len(INDICATOR_REGISTRY)
    by_category = {}
    requires_volume = 0
    batch_capable = 0
    
    for info in INDICATOR_REGISTRY.values():
        # Category count
        cat = info['category']
        cat_str = str(cat).split('.')[-1]  # IndicatorCategory.MOMENTUM -> MOMENTUM
        by_category[cat_str] = by_category.get(cat_str, 0) + 1
        
        # Volume requirement
        if info['requires_volume']:
            requires_volume += 1
        
        # Batch capable
        if info.get('has_calculate_batch', False):
            batch_capable += 1
    
    return {
        'total_indicators': total,
        'by_category': by_category,
        'requires_volume': requires_volume,
        'batch_capable': batch_capable,
        'categories': get_categories()
    }


__all__ = [
    'INDICATOR_REGISTRY',
    'get_indicator_class',
    'list_indicators',
    'get_batch_capable_indicators',
    'get_categories',
    'get_indicator_info',
    'get_registry_statistics',
]
