#!/usr/bin/env python3
"""
components/strategies/templates/donchian_new.py
SuperBot - donchian
Generated by WebUI
Version: 1.0.0

donchian strategy
"""

import sys
from pathlib import Path

# SuperBot base directory'yi path'e ekle
base_dir = Path(__file__).parent.parent.parent.parent
sys.path.insert(0, str(base_dir))

from components.strategies.base_strategy import (
    BaseStrategy,
    SymbolConfig,
    TechnicalParameters,
    RiskManagement,
    ExitStrategy,
    PositionManagement,
    TradingSide,
    PositionSizeMethod,
    ExitMethod,
    StopLossMethod
)


class Strategy(BaseStrategy):
    """
    donchian

    donchian strategy
    """

    def __init__(self):
        super().__init__()

        # STRATEGY METADATA
        self.strategy_name = "donchian"
        self.strategy_version = "1.0.0"
        self.description = "donchian strategy"
        self.author = "SuperBot Team"
        self.created_date = "2026-01-22"
        self.warmup_period = 200

        # BACKTEST CONFIGURATION
        self.backtesting_enabled = True
        self.backtest_start_date = "2025-01-05T00:00"
        self.backtest_end_date = "2025-03-30T00:00"
        self.initial_balance = 10000
        self.download_klines = False
        self.update_klines = False

        # BACKTEST PARAMETERS
        self.backtest_parameters = {
            "min_spread": 0.0001,
            "commission": 0.0002,
            "max_slippage": 0.0005
        }


        # TRADING CONFIGURATION
        self.side_method = TradingSide.BOTH
        self.leverage = 1
        # Timeframe configuration
        self.primary_timeframe = "5m"
        self.mtf_timeframes = ['5m', '15m']

        self.set_default_leverage = False
        self.hedge_mode = False
        self.set_margin_type = False
        self.margin_type = "isolated"

        # SYMBOLS
        self.symbol_source = "strategy"
        self.symbols = [
            SymbolConfig(
                symbol=['BTC', 'BNB', 'ETH', 'SOL', 'AVAX', 'LINK', 'BCH', 'ZEC', 'DOT', 'ADA'],
                quote="USDT",
                enabled=True
            )
        ]

        # RISK MANAGEMENT
        self.risk_management = RiskManagement(
            sizing_method=PositionSizeMethod.FIXED_PERCENT,
            position_percent_size=1,
            position_usd_size=300.0,
            position_quantity_size=2.0,
            max_risk_per_trade=2.5,

            max_correlation=0.6,
            position_correlation_limit=0.7,
            max_drawdown=100,
            max_daily_trades=800,
            emergency_stop_enabled=True,
            ai_risk_enabled=False,
            dynamic_position_sizing=True,
        )

        # POSITION MANAGEMENT
        self.position_management = PositionManagement(
            max_positions_per_symbol=1,
            max_total_positions=400,
            allow_hedging=False,
            position_timeout_enabled=True,
            position_timeout=1800,
            pyramiding_enabled=False,
            pyramiding_max_entries=3,
            pyramiding_scale_factor=0.5
        )

        # EXIT STRATEGY
        self.exit_strategy = ExitStrategy(
            # Take Profit
            take_profit_method=ExitMethod.FIXED_PERCENT,
            take_profit_percent=2,
            take_profit_price=0.0,
            take_profit_risk_reward_ratio=2.0,
            take_profit_atr_multiplier=3.0,
            take_profit_fib_level=1.618,
            take_profit_ai_level=1,

            # Stop Loss
            stop_loss_method=StopLossMethod.FIXED_PERCENT,
            stop_loss_percent=1,
            stop_loss_price=0.0,
            stop_loss_atr_multiplier=2.0,
            stop_loss_swing_lookback=10,
            stop_loss_fib_level=0.382,
            stop_loss_ai_level=1,

            # Trailing Stop
            trailing_stop_enabled=True,
            trailing_activation_profit_percent=1,
            trailing_callback_percent=0.3,
            trailing_take_profit=False,
            trailing_distance=0.2,

            # Break-even
            break_even_enabled=True,
            break_even_trigger_profit_percent=1.4,
            break_even_offset=0.9,

            # Partial Exit
            partial_exit_enabled=True,
            partial_exit_levels=[3, 4, 10],
            partial_exit_sizes=[0.4, 0.4, 0.2],
        )

        # TECHNICAL INDICATORS
        self.technical_parameters = TechnicalParameters(
            indicators={
                "ema_50": {
                    "period": 50,
                },
                "adx_14": {
                    "adx_threshold": 25,
                    "period": 14,
                },
                "rsi_14": {
                    "overbought": 75,
                    "oversold": 20,
                    "period": 14,
                },
                "donchian_20": {
                    "period": 20,
                },
            }
        )

        # ENTRY CONDITIONS
        self.entry_conditions = {
            "long": [
                ['close', '>', 'ema_50'],
                ['rsi_14', 'crossunder', 75],
                ['close', 'crossover', 'donchian_20_upper'],
            ],
            "short": [
                ['close', '<', 'ema_50'],
                ['rsi_14', 'crossover', 20],
            ],
        }

        # EXIT CONDITIONS
        self.exit_conditions = {
            "long": [
            ],
            "short": [
            ],
            "stop_loss": [
            ],
            "take_profit": [
            ],
        }

        # CUSTOM PARAMETERS
        self.custom_parameters = {
            "news_filter": False,

            # Session Filter
            "session_filter": {
                "enabled": False,
                "sydney": False,
                "tokyo": False,
                "london": True,
                "new_york": True,
                "london_ny_overlap": True,
            },

            # Time Filter
            "time_filter": {
                "enabled": False,
                "start_hour": 8,
                "end_hour": 21,
                "exclude_hours": [],
            },

            # Day Filter
            "day_filter": {
                "enabled": False,
                "monday": False,
                "tuesday": False,
                "wednesday": True,
                "thursday": True,
                "friday": True,
                "saturday": True,
                "sunday": True,
            },
        }

        # OPTIMIZER PARAMETERS
        # Format: (min, max, step) for numeric or [choice1, choice2] for categorical
        #
        # MULTI-STAGE OPTIMIZATION STRATEGY:
        # Set 'enabled': False to skip a stage, True to activate it
        #
        # Stage 1: Risk Management (50-100 trials)
        #   - Optimize position sizing first (most critical)
        #   - indicators: enabled=False, exit_strategy: enabled=False, risk_management: enabled=True
        #
        # Stage 2: Exit Strategy (50-100 trials)
        #   - Use best risk params from Stage 1 (apply manually)
        #   - Optimize TP/SL/break-even/trailing
        #   - indicators: enabled=False, exit_strategy: enabled=True, risk_management: enabled=False
        #
        # Stage 3: Indicators (100-200 trials)
        #   - Use best risk + exit params from Stage 1+2 (apply manually)
        #   - Optimize indicator periods and thresholds
        #   - indicators: enabled=True, exit_strategy: enabled=False, risk_management: enabled=False
        #
        # Stage 4: Fine-tune (50 trials) - Optional
        #   - Set all enabled=True
        #   - Use small ranges around best values from previous stages
        #
        self.optimizer_parameters = {
            # ================================================================
            # STAGE 0: Main Strategy Parameters
            # ================================================================
            'main_strategy': {
                'enabled': False,
                #'side_method': ['BOTH', 'LONG', 'SHORT'],
                #'leverage': (1, 20, 1),
            },

            # ================================================================
            # STAGE 1: Risk Management (PRIORITY: HIGHEST)
            # ================================================================
            'risk_management': {
                'enabled': False,
                #'sizing_method': ['FIXED_PERCENT', 'RISK_BASED', 'FIXED_USD'],
                #'position_percent_size': (5.0, 20.0, 1),
                #'position_usd_size': (100, 1000, 100),
                #'max_risk_per_trade': (1.0, 5.0, 0.5),
            },

            # ================================================================
            # STAGE 2: Exit Strategy (PRIORITY: HIGH)
            # ================================================================
            'exit_strategy': {
                'enabled': False,
                #'stop_loss_method': ['FIXED_PERCENT', 'ATR_BASED', 'FIBONACCI'],
                #'stop_loss_percent': (0.8, 2.0, 0.1),
                #'take_profit_method': ['FIXED_PERCENT', 'RISK_REWARD', 'ATR_BASED'],
                #'take_profit_percent': (2.4, 5.2, 0.2),
                #'break_even_enabled': [True, False],
                #'break_even_trigger_profit_percent': (0.8, 2.0, 0.2),
                #'break_even_offset': (0.05, 0.30, 0.05),
                #'trailing_stop_enabled': [True, False],
                #'trailing_activation_profit_percent': (1.0, 3.0, 0.5),
                #'trailing_callback_percent': (0.3, 1.0, 0.1),
            },

            # ================================================================
            # STAGE 3: Indicators (PRIORITY: MEDIUM)
            # ================================================================
            'indicators': {
                'enabled': False,
                #'ema': {
                #    'period': (25, 100, 1),  # Period range (default: 50)
                #},
                #'adx': {
                #    'period': (7, 28, 1),  # Period range (default: 14)
                #    'threshold': (17, 32, 5),
                #},
                #'rsi': {
                #    'period': (7, 28, 1),  # Period range (default: 14)
                #    'overbought': (65, 80, 5),
                #    'oversold': (20, 35, 5),
                #},
                #'donchian': {
                #    'period': (10, 40, 1),  # Period range (default: 20)
                #},
            },

            # ================================================================
            # STAGE 4: Position Management (PRIORITY: LOW)
            # ================================================================
            'position_management': {
                'enabled': False,
                #'max_total_positions': (1, 5, 1),
                #'max_positions_per_symbol': (1, 3, 1),
                #'pyramiding_enabled': [True, False],
                #'pyramiding_max_entries': (2, 5, 1),
            },

            # ================================================================
            # STAGE 5: Market Filters (PRIORITY: LOW)
            # ================================================================
            'market_filters': {
                'enabled': False,
                #'day_filter_enabled': [True, False],
                #'monday_enabled': [True, False],
                #'tuesday_enabled': [True, False],
            },

            # ================================================================
            # GLOBAL CONSTRAINTS
            # ================================================================
            'constraints': {
                'max_combinations': 10000,
                'min_trades': 20,
                'min_sharpe': 0.5,
                'min_profit_factor': 1.0,
                'max_drawdown': 30.0,
                'timeout_per_backtest': 300,
            },
        }
