config:
  entry_model:
    direction:
      enabled: true
    enabled: true
    filter:
      enabled: true
      require_match: true
      threshold: 0.5
    lightgbm:
      learning_rate: 0.1
      max_depth: 6
      n_estimators: 100
      num_leaves: 31
      subsample: 0.8
    lstm:
      bidirectional: false
      dropout: 0.2
      hidden_size: 128
      num_layers: 2
    mode: filter
    type: xgboost
    xgboost:
      colsample_bytree: 0.8
      learning_rate: 0.05
      max_depth: 6
      n_estimators: 100
      subsample: 0.8
  training:
    iterative:
      convergence_threshold: 0.01
      freeze_after_convergence: true
      max_rounds: 3
    optimization:
      enabled: false
      method: optuna
      metric: sharpe_ratio
      n_trials: 50
    split:
      method: time_based
      test_ratio: 0.15
      train_ratio: 0.7
      val_ratio: 0.15
      walk_forward:
        gap_bars: 100
        n_folds: 5
    strategy: iterative
created_at: '2026-01-29T22:27:18.064193'
feature_names:
- ema_50
- adx_14_adx
- adx_14_plus_di
- adx_14_minus_di
- rsi_14
- ema_distance
- price_momentum
- rsi_change
- rsi_slope
- stochrsi_14_stoch_rsi
- stochrsi_14_k
- stochrsi_14_d
- stochrsi_14_crossover
- cci_20
- volume_change
- volume_spike
- obv_change
- atr_14
- atr_change
- bb_width_upper
- bb_width_middle
- bb_width_lower
- close_pct
- hl_range
metrics:
  test:
    accuracy: 0.5164609053497943
    f1_score: 0.5884413309982487
    false_negatives: 141
    false_positives: 94
    precision: 0.6412213740458015
    recall: 0.5436893203883495
    roc_auc: 0.5028065748816118
    true_negatives: 83
    true_positives: 168
  train:
    accuracy: 0.9411764705882353
    f1_score: 0.9521472392638037
    false_negatives: 147
    false_positives: 9
    precision: 0.994234465086483
    recall: 0.9134785167745733
    roc_auc: 0.9944501641913922
    true_negatives: 944
    true_positives: 1552
  val:
    accuracy: 0.7954070981210856
    f1_score: 0.8268551236749117
    false_negatives: 76
    false_positives: 22
    precision: 0.9140625
    recall: 0.7548387096774194
    roc_auc: 0.9275625119297575
    true_negatives: 147
    true_positives: 234
model_type: xgboost
strategy_name: simple_rsi
test_samples: 486
train_samples: 2652
val_samples: 479
